ADELA:
  - アデラ
Ariana Grande:
  - アリアナ・グランデ
Bruno Mars:
  - ブルーノ・マーズ
Drake:
  - ドレイク
Dolly Parton:
  - ドリー・パートン
Dominic Fike:
  - ドミニク・ファイク
Lil Baby:
  - リル・ベイビー
Mac Miller:
  - マック・ミラー
Miley:
  - マイリー・サイラス
Olivia Dean:
  - オリヴィア・ディーン
Olivia Rodrigo:
  - オリヴィア・ロドリゴ
PARTYNEXTDOOR:
  - パーティーネクストドア
Noah Kahan:
  - ノア・カーン
Teddy Swims:
  - テディ・スウィムズ
Taylor Swift:
  - テイラー・スウィフト
Kacey Musgraves:
  - ケイシー・マスグレイヴス
Kenny Chesney:
  - ケニー・チェズニー
21 Savage:
  - 21サヴェージ
Jhene Aiko:
  - ジェネイ・アイコ
