- billboard_title: I Knew It, I Knew You
  apple_titles:
    - 'I Knew It, I Knew You (From "Toy Story 5")'
  apple_artists: []
- billboard_title: BbY WOW
  apple_titles: [BbY WOW]
  apple_artists: ['KAROL G, Judeline & rusowsky']
  apple_urls:
    - https://music.apple.com/us/song/6796864754
- billboard_title: Dead Fresh
  apple_titles: [Dead Fresh]
  apple_artists: [リル・ベイビー]
  apple_urls:
    - https://music.apple.com/jp/album/dead-fresh-single/6791695694?i=6791695695
    - https://music.apple.com/jp/album/dead-fresh-single/6790569132?i=6790569133
- billboard_title: Babydoll
  apple_titles: [Babydoll]
  apple_artists: [ドミニク・ファイク]
  apple_urls:
    - https://music.apple.com/jp/album/babydoll/1438243719?i=1438243880
- billboard_title: 9 To 5
  apple_titles: [9 to 5]
  apple_artists: [ドリー・パートン]
  apple_urls:
    - https://music.apple.com/jp/album/9-to-5/1641622888?i=1641626089
- billboard_title: Janice STFU
  apple_titles: [Janice STFU]
  apple_artists: [ドレイク]
  apple_urls:
    - https://music.apple.com/jp/album/janice-stfu/6769568449?i=6769568596
- billboard_title: Jolene
  apple_titles: [Jolene]
  apple_artists: [ドリー・パートン]
  apple_urls:
    - https://music.apple.com/jp/album/jolene/216344884?i=216345135
- billboard_title: Hate That I Made You Love Me
  apple_titles:
    - hate that i made you love me
  apple_artists:
    - アリアナ・グランデ
- billboard_title: So Easy (To Fall In Love)
  apple_titles:
    - So Easy (To Fall In Love)
  apple_artists:
    - オリヴィア・ディーン
- billboard_title: I Can't Love You Anymore
  apple_titles:
    - I Can't Love You Anymore
  apple_artists:
    - Ella Langley & Morgan Wallen
- billboard_title: Man I Need
  apple_titles:
    - Man I Need
  apple_artists:
    - オリヴィア・ディーン
- billboard_title: Risk It All
  apple_titles:
    - Risk It All
  apple_artists:
    - ブルーノ・マーズ
- billboard_title: Dai Dai (FIFA World Cup Official Song 2026)
  apple_titles: [Dai Dai]
  apple_artists:
    - Shakira
    - Shakira & Burna Boy
    - シャキーラ & バーナ・ボーイ
- billboard_title: Jaded
  apple_titles: [Jaded]
  apple_artists:
    - Koe Wetzel & Ella Langley
- billboard_title: Islands In The Stream
  apple_titles:
    - Islands In the Stream
  apple_artists:
    - Dolly Parton
    - ドリー・パートン
    - Dolly Parton, Kenny Rogers
    - Dolly Parton & Kenny Rogers
    - ドリー・パートン, ケニー・ロジャース
    - ドリー・パートン & ケニー・ロジャース
  apple_urls:
    - https://music.apple.com/jp/album/islands-in-the-stream/282883573?i=282883594
- billboard_title: I Will Always Love You
  apple_titles: [I Will Always Love You]
  apple_artists:
    - Dolly Parton
    - ドリー・パートン
  apple_urls:
    - https://music.apple.com/jp/album/i-will-always-love-you/282883573?i=282883579
- billboard_title: Still
  apple_titles: [Still]
  apple_artists:
    - KAROL G & Bruno Mars
- billboard_title: Ahí
  apple_titles: [Ahí]
  apple_artists:
    - KAROL G & Drake
- billboard_title: Phone, Keys, Wallet
  apple_titles: ['Phone, Keys, Wallet']
  apple_artists:
    - Lainey Wilson & John Mayer
- billboard_title: Rein Me In
  apple_titles: [Rein Me In]
  apple_artists:
    - Sam Fender & Olivia Dean
    - サム・フェンダー & オリヴィア・ディーン
  apple_urls:
    - https://music.apple.com/jp/album/rein-me-in/1820918466?i=1820918468
- billboard_title: Hit The Wall
  apple_titles: [Hit the Wall]
  apple_artists:
    - グレイシー・エイブラムス
  apple_urls:
    - https://music.apple.com/jp/album/hit-the-wall/6766750836?i=6766750846
- billboard_title: Great Expectation
  apple_titles: [Great Expectation]
  apple_artists:
    - シエナ・スパイロ
  apple_urls:
    - https://music.apple.com/jp/album/great-expectation/6769552402?i=6769552411
- billboard_title: Love Bomb
  apple_titles:
    - Love Bomb
  apple_artists:
    - Jhene Aiko & Ab-Soul
    - ジェネイ・アイコ & Ab-Soul
  apple_urls:
    - https://music.apple.com/jp/album/love-bomb/6810715695?i=6810716019
- billboard_title: Ceiling
  apple_titles:
    - Ceiling (Freestyle)
  apple_artists:
    - Jhene Aiko
    - ジェネイ・アイコ
  apple_urls:
    - https://music.apple.com/jp/album/ceiling-freestyle/6810715695?i=6810716020
- billboard_title: So Good
  apple_titles:
    - So Good (feat. Kendrick Lamar)
  apple_artists:
    - Jhene Aiko
    - ジェネイ・アイコ
  apple_urls:
    - https://music.apple.com/jp/album/so-good-feat-kendrick-lamar/6810715695?i=6810716062
- billboard_title: Cinderella
  apple_titles:
    - Cinderella (feat. Ty Dolla $ign)
  apple_artists:
    - Mac Miller
    - マック・ミラー
  apple_urls:
    - https://music.apple.com/jp/album/cinderella-feat-ty-dolla-%24ign/1137965822?i=1137966332
- billboard_title: Morning Dew (Donk)
  apple_titles: [MORNING DEW (DONK)]
  apple_artists: [Beyoncé]
  apple_urls:
    - https://music.apple.com/jp/album/morning-dew-donk/6787303151?i=6787303156
- billboard_title: Something To Lose
  apple_titles: [Something To Lose]
  apple_artists: [STELLA LEFTY & ヴィンセント・メイソン]
  apple_urls:
    - https://music.apple.com/jp/album/something-to-lose/6783994651?i=6783994835
- billboard_title: Raindance
  apple_titles: [Raindance]
  apple_artists: [デイヴ & Tems]
  apple_urls:
    - https://music.apple.com/jp/album/raindance/1847992481?i=1847992612
- billboard_title: Cowgirl
  apple_titles: [Cowgirl]
  apple_artists: [シャブージー]
  apple_urls:
    - https://music.apple.com/jp/album/cowgirl/6771920973?i=6771920974
    - https://music.apple.com/jp/album/the-outlaw-cherie-lee-other-western-tales/1894906682?i=1894906692
- billboard_title: Mexico Honey
  apple_titles: [Mexico Honey]
  apple_artists: [ケイシー・マスグレイヴス]
  apple_urls:
    - https://music.apple.com/jp/album/mexico-honey/1883176984?i=1883177272
- billboard_title: Animal
  apple_titles: [Animal]
  apple_artists: [KATSEYE]
  apple_urls:
    - https://music.apple.com/jp/album/animal/1891779764?i=1891779776
- billboard_title: WTF GOIN
  apple_titles: [WTF GOIN]
  apple_artists: ["Belly Gang Kushington & 21サヴェージ"]
  apple_urls:
    - https://music.apple.com/jp/album/wtf-goin/6779378647?i=6779378648
    - https://music.apple.com/jp/album/wtf-goin/6779392179?i=6779392180
